package northwind.dto;
// Generated Jan 22, 2016 12:15:57 AM by Hibernate Tools 4.0.0

/**
 * CustomerCustomerDemo generated by hbm2java
 */
public class CustomerCustomerDemo implements java.io.Serializable {

	private static final long serialVersionUID = -8704446178713734268L;

	private CustomerCustomerDemoId id;

	public CustomerCustomerDemo() {
	}

	public CustomerCustomerDemo(CustomerCustomerDemoId id) {
		this.id = id;
	}

	public CustomerCustomerDemoId getId() {
		return this.id;
	}

	public void setId(CustomerCustomerDemoId id) {
		this.id = id;
	}
}