package northwind.dto;
// Generated Jan 22, 2016 12:15:57 AM by Hibernate Tools 4.0.0

/**
 * EmployeeTerritories generated by hbm2java
 */
public class EmployeeTerritories implements java.io.Serializable {

	private static final long serialVersionUID = 4381958954363092290L;

	private EmployeeTerritoriesId id;

	public EmployeeTerritories() {
	}

	public EmployeeTerritories(EmployeeTerritoriesId id) {
		this.id = id;
	}

	public EmployeeTerritoriesId getId() {
		return this.id;
	}

	public void setId(EmployeeTerritoriesId id) {
		this.id = id;
	}
}