package northwind.dto;
// Generated Jan 22, 2016 12:15:57 AM by Hibernate Tools 4.0.0

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private static final long serialVersionUID = 3088560265554263889L;

	private short productId;
	private String productName;
	private Short supplierId;
	private Short categoryId;
	private String quantityPerUnit;
	private Float unitPrice;
	private Short unitsInStock;
	private Short unitsOnOrder;
	private Short reorderLevel;
	private int discontinued;

	public Products() {
	}

	public Products(short productId, String productName, int discontinued) {
		this.productId = productId;
		this.productName = productName;
		this.discontinued = discontinued;
	}

	public Products(short productId, String productName, Short supplierId, Short categoryId, String quantityPerUnit,
			Float unitPrice, Short unitsInStock, Short unitsOnOrder, Short reorderLevel, int discontinued) {
		this.productId = productId;
		this.productName = productName;
		this.supplierId = supplierId;
		this.categoryId = categoryId;
		this.quantityPerUnit = quantityPerUnit;
		this.unitPrice = unitPrice;
		this.unitsInStock = unitsInStock;
		this.unitsOnOrder = unitsOnOrder;
		this.reorderLevel = reorderLevel;
		this.discontinued = discontinued;
	}

	public short getProductId() {
		return this.productId;
	}

	public void setProductId(short productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public Short getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(Short supplierId) {
		this.supplierId = supplierId;
	}

	public Short getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Short categoryId) {
		this.categoryId = categoryId;
	}

	public String getQuantityPerUnit() {
		return this.quantityPerUnit;
	}

	public void setQuantityPerUnit(String quantityPerUnit) {
		this.quantityPerUnit = quantityPerUnit;
	}

	public Float getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Float unitPrice) {
		this.unitPrice = unitPrice;
	}

	public Short getUnitsInStock() {
		return this.unitsInStock;
	}

	public void setUnitsInStock(Short unitsInStock) {
		this.unitsInStock = unitsInStock;
	}

	public Short getUnitsOnOrder() {
		return this.unitsOnOrder;
	}

	public void setUnitsOnOrder(Short unitsOnOrder) {
		this.unitsOnOrder = unitsOnOrder;
	}

	public Short getReorderLevel() {
		return this.reorderLevel;
	}

	public void setReorderLevel(Short reorderLevel) {
		this.reorderLevel = reorderLevel;
	}

	public int getDiscontinued() {
		return this.discontinued;
	}

	public void setDiscontinued(int discontinued) {
		this.discontinued = discontinued;
	}
}